name: 도커 CI/CD 파이프라인

#on:
#  push:
#    branches:
#      - wideview-deploy
#      - wideview

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v1

      - name: Docker Hub에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: .env 파일 생성
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Docker 이미지 빌드 및 Docker Hub에 푸시
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: judykimsohui/nemo-dev-fe:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: SSH를 위한 디렉토리 및 키 설정
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEV_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 서버에 SSH 접속 및 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # /app/config 디렉토리 생성 및 권한 설정
            if [ ! -d "/app/config" ]; then
              sudo mkdir -p /app/config
            fi
            sudo chown -R $USER:$USER /app/config

            # .env 파일 생성
            echo "${{ secrets.ENV_FILE }}" | sudo tee /app/config/.env

            # Docker 이미지 최신 버전 가져오기
            docker pull judykimsohui/nemo-dev-fe:latest

            # 이전에 실행 중인 nemo-dev-fe 컨테이너 중지 및 제거
            docker stop nemo-dev-fe || true
            docker rm nemo-dev-fe || true

            # 새로운 Docker 컨테이너 실행
            docker run -d --name nemo-dev-fe -p 4000:4000 \
              --env-file /app/config/.env \
              judykimsohui/nemo-dev-fe:latest

            # 컨테이너 상태 확인 및 로그 출력
            docker ps -a
            docker logs nemo-dev-fe || echo "컨테이너 로그가 없습니다."
